### ISSUE TITLE
Should the server redirect paths to directories?

### ISSUE THREAD

**Issue by za419** [za419/cadence-server#20]
If one were using the server to serve "cadenceradio.com", a user accessing "cadenceradio.com/original" would see the file "cadenceradio.com/original/index.html"

Now - Stripping the "index.html" part (serving "cadenceradio.com/original/index.html" on "cadenceradio.com/original/") is pretty standard. But most servers would redirect the file-looking interface "/original" to the directory-looking interface "/original/".

So my question here is, should we change the behavior to look for this and perform the redirect, or do we not care?

Open for comments, especially from @kenellorando, @Karenwithakay, and @JakobFrank.

**Comment by kenellorando** [comment]
We should perform the redirect to directories.

**Comment by za419** [comment]
By your command.
