### ISSUE TITLE
Don't require server maintainers to manually create the logging directory

### ISSUE THREAD

**Issue by za419** [za419/cadence-server#23]
It should be possible - fairly simple even - to make sure the directory we're writing logs into exists so that the server doesn't crash if the importer doesn't manually create that directory.

**Comment by kenellorando** [comment]
I'm thinking of doing the start script which could create our directories, then start the server.

**Comment by kenellorando** [comment]
Ok I'm on this. But I need to know the arguments we need to pass to the server.

**Comment by za419** [comment]
I had a similar idea about a start script. I wasn't quite going to start yet 

I was going to have the server itself do this. But that's fine

The command line is `python server.py <port> <path to directory> [-c [seconds]]`

It requires a python 3 version (not precisely sure which, but I'd guess 3.5 is fine).

Port is obviously which port to serve the site on. If it's something privileged like 80, the server will require sudo

The path to directory is the path to the root of the site (ie, the front-end folder). I've only tested it with absolute paths, but I've recently rewritten it so it should work just as well with relative ones. 

Those two are the only mandatory flags. If you provide `-c` (which I recommend), the server will instruct browsers that they are permitted to cache resources, thus reducing the amount of data they'll need to download to refetch cadence. You can provide an integer after that flag to set the number of seconds browsers are told cache resources are fresh for, or you can leave it to use the default (currently 3600).

Logs are stored next to the server itself, in a folder called "logs"

**Comment by kenellorando** [comment]
Ok, perfect. Thanks for that info. 

A script is ideal as it may used later to fire up music stream software as well.

**Comment by za419** [comment]
You're welcome. 

Yes, that was my intent as well. 

I just think that the server shouldn't *have* to be run by a script, so I want to have the server make sure it doesn't crash by making sure the folder exists
